org.gradle.jvmargs=-Xmx3072M

minecraft_version=1.21.3
enabled_platforms=fabric,forge,neoforge
supported_minecraft_version=>=1.21.2 <1.21.4

archives_base_name=paladin-furniture-mod
mod_version=1.4.2
maven_group=com.unlikepaladin

architectury_version=14.0.4

fabric_loader_version=0.16.9
fabric_api_version=0.109.0+1.21.3
yarn_mappings=1.21.3+build.2

forge_version=1.21.3-53.0.25

neoforge_version=21.3.65
yarn_mappings_patch_neoforge_version=1.21+build.4
#Mod Dependencies
rei_version=17.0.792
patchouli_version_fabric=1.21-87-FABRIC
sandwichable_version=1.3.1+1.20.1
spruceui_version=5.0.0+1.20
sandwichable_compatibility=false
rei_compatibility=true
patchouli_compatibility=false
arrp_version=4605834
arrp_compatibility=false
cloth_config_compatibility=false
modmenu_version=12.0.0-beta.1
jei_version=19.21.0.246
patchouli_version_forge=1.21-87-NEOFORGE
immersive_portals_compatibility_fabric=false
immersive_portals_version_fabric=v6.0.3-mc1.21.1
immersive_portals_compatibility_forge=false
immersive_portals_version_forge=4477738
dimlib_version_fabric=v1.1.0-mc1.21.1
lazy_dfu_enabled=false
lazy_dfu_version_fabric=0.1.3
lazy_dfu_version_forge=4327266
terrestria=6.3.0
iris_version=1.8.0+1.21.3-fabric
oculus_version=1.8.0+1.21.3-neoforge
jei_compatibility=false
cookingforblockheads_version_fabric=5862903
cookingforblockheads_version_forge=5856839
cookingforblockheads_version_neoforge=5862907
cookingfor_blockheads_compatibility_forge=false
cookingfor_blockheads_compatibility_fabric=false
cookingfor_blockheads_compatibility_neoforge=true
balm_version_fabric=5848095
balm_version_forge=5798248
balm_version_neoforge=5848102
farmers_delight_version_fabric=1.21.1-3.0.1
farmers_delight_version_forge=5772720
emi_version=1.1.18+1.21.1
emi_compatibility=false
cloth_config_version=16.0.141

loom.ignoreDependencyLoomVersionValidation=true