pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://files.minecraftforge.net/maven/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'paladin-furniture-mod'

include 'common'
include 'fabric'
include 'neoforge'
include 'forge'

