name: Publish on GitHub, CurseForge & Modrinth    #The name of your GitHub Action on github.com

on: [workflow_dispatch ]           #'workflow_dispatch' -> allows manual execution through github.com

env:
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN  }}
  GITHUB_TOKEN: ${{ secrets.PB_GITHUB_TOKEN }}
permissions:
  contents: write

jobs:
  build_and_publish:
    name: Build and Publish (Github, Modrinth, CF)
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          check-latest: true

      - name: Validate Gradle wrapper
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew clean build

      - name: Extract Minecraft Version from Branch
        run: echo "MINECRAFT_VERSION=${GITHUB_REF_NAME#architectury-}" >> $GITHUB_ENV

      - name: Extract Mod Version from Gradle Properties
        uses: BrycensRanch/read-properties-action@v1.0.4
        id: mod_version
        with:
          file: gradle.properties
          property: mod_version
          default: 1.4

      - name: Publish (CurseForge/Modrinth) - Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 663141
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: SISz7Qd3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: "Paladin's Furniture Mod ${{steps.mod_version.outputs.mod_version}} for Minecraft ${{env.MINECRAFT_VERSION}} - Forge"
          version: "${{env.MINECRAFT_VERSION}}-v${{steps.mod_version.outputs.mod_version}}-minecraftforge"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: forge

          files: forge/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar

      - name: Publish (CurseForge/Modrinth) - Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 663141
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: SISz7Qd3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: "Paladin's Furniture Mod ${{steps.mod_version.outputs.value}} for Minecraft ${{env.MINECRAFT_VERSION}} - Fabric"
          version: "${{env.MINECRAFT_VERSION}}-v${{steps.mod_version.outputs.value}}-fabric"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          dependencies: fabric-api | depends | *

          files: fabric/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar

      - name: Publish (CurseForge/Modrinth) - NeoForge
        if: ${{ hashFiles('neoforge/build/libs') != '' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 663141
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: SISz7Qd3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: "Paladin's Furniture Mod ${{steps.mod_version.outputs.value}} for Minecraft ${{env.MINECRAFT_VERSION}} - NeoForge"
          version: "${{env.MINECRAFT_VERSION}}-v${{steps.mod_version.outputs.value}}-neoforge"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: neoforge
          dependencies: fabric-api | depends | *

          files: neoforge/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar

      - name: Publish (GitHub) - All Loaders
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "v${{env.MINECRAFT_VERSION}}-v${{steps.mod_version.outputs.value}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "Paladin's Furniture Mod ${{steps.mod_version.outputs.value}} for Minecraft ${{env.MINECRAFT_VERSION}}"
          version: "${{env.MINECRAFT_VERSION}}-v${{steps.mod_version.outputs.value}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: |
            fabric
            forge
            neoforge

          files: |
            fabric/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar
            forge/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar
            neoforge/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar
