name: Publish on GitHub, CurseForge & Modrinth    #The name of your GitHub Action on github.com

on: [workflow_dispatch ]           #'workflow_dispatch' -> allows manual execution through github.com

env:
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN  }}
  GITHUB_TOKEN: ${{ secrets.PB_GITHUB_TOKEN }}
  MOD_VERSION: 1.4
permissions:
  contents: write

jobs:
  build_and_publish:
    name: Build and Publish (Github, Modrinth, CF)
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Validate Gradle wrapper
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          check-latest: true

      - name: Build
        run: ./gradlew clean build

      - name: Extract Minecraft Version from Branch
        run: echo "MINECRAFT_VERSION=${GITHUB_REF_NAME#architectury-}" >> $GITHUB_ENV

      - name: Publish (CurseForge/Modrinth/GitHub) - Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 663141
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: SISz7Qd3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "Paladin's Furniture Mod ${{env.MOD_VERSION}} for Minecraft ${{env.MINECRAFT_VERSION}} - Forge"
          version: "${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}-minecraftforge"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: forge
          game-versions: "${{env.MINECRAFT_VERSION}}"

          github-name: "Paladin's Furniture Mod ${{env.MOD_VERSION}} for Minecraft ${{env.MINECRAFT_VERSION}}"
          github-version: "${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}"

          files: forge/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar

      - name: Publish (CurseForge/Modrinth/GitHub) - Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 663141
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: SISz7Qd3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "Paladin's Furniture Mod ${{env.MOD_VERSION}} for Minecraft ${{env.MINECRAFT_VERSION}} - Fabric"
          version: "${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}-fabric"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          dependencies: fabric-api | depends | *

          github-name: "Paladin's Furniture Mod ${{env.MOD_VERSION}} for Minecraft ${{env.MINECRAFT_VERSION}}"
          github-version: "${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}"

          files: fabric/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar

      - name: Publish (CurseForge/Modrinth/GitHub) - NeoForge
        if: ${{ hashFiles('neoforge/build/libs') != '' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 663141
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: SISz7Qd3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "Paladin's Furniture Mod ${{env.MOD_VERSION}} for Minecraft ${{env.MINECRAFT_VERSION}} - NeoForge"
          version: "${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}-neoforge"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: neoforge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          dependencies: fabric-api | depends | *

          github-name: "Paladin's Furniture Mod ${{env.MOD_VERSION}} for Minecraft ${{env.MINECRAFT_VERSION}}"
          github-version: "${{env.MINECRAFT_VERSION}}-v${{env.MOD_VERSION}}"

          files: neoforge/build/libs/!(*-@(dev|sources|all|dev-shadow|javadoc|transformProduction*)).jar
